services:

  mysql:
    image: mysql:8.0
    container_name: container_sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nats:
    image: nats:2.10-alpine
    container_name: container_nats
    ports:
      - "4222:4222"

  service-authentication:
    build: ./service-authentication
    container_name: container_auth
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - nats
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/auth_db
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - NATS_URL=nats://nats:4222

  service-agent:
    build: ./service-agent
    container_name: container_agent
    ports:
      - "8004:8000"
    depends_on:
      - mysql
      - nats
      - service-authentication
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/bank_db
      - NATS_URL=nats://nats:4222

  service-client:
    build: service-client
    container_name: container_client
    ports:
      - "8001:8000"
    depends_on:
      - mysql
      - nats
      - service-authentication
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/bank_db
      - AUTH_SERVICE_URL=http://service-authentication:8000
      - NATS_URL=nats://nats:4222

  service-logs:
    build: ./service-logs
    container_name: container_logs
    ports:
      - "8005:8000"
    depends_on:
      - mysql
      - nats
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/logs_db
      - NATS_URL=nats://nats:4222

volumes:
  mysql_data:
